version: '3'
services:
    api_nginx_blog:
        container_name: api_nginx_blog
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./api:/var/www/html
            - ./nginx_api/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api_blog
    app_nginx_blog:
        container_name: app_nginx_blog
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./api:/var/www/html
            - ./nginx_app/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app_blog
    api_blog:
        build: ./api
        container_name: api_blog
        volumes:
            - ./api:/var/www/html
        depends_on:
            - db_blog
    app_blog:
        build: ./app    
        container_name: app_blog
        tty: true
        volumes:
            - ./app:/home/app
        environment:
            PORT: '80'
            HOST: '0.0.0.0'
    db_blog:
        image: mysql:5.7
        container_name: db_blog
        restart: always
        volumes:
            - ./mysql_lib:/var/lib/mysql
            - ./mysql_conf:/etc/mysql/conf.d
        environment:
                MYSQL_DATABASE: selfIntro
                MYSQL_USER: selfIntro
                MYSQL_PASSWORD: self%Wgg-Intro
                MYSQL_ROOT_PASSWORD: self%Wgg-Intro
                TZ: "Asia/Tokyo"
        command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
        ports:
            - 3306:3306
